config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books
  resources :users, only: [:index, :show, :edit, :update]
  root to: 'homes#top'
  get 'homes/about', as: 'about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, :body, presence: true
  validates :body, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image

  validates :profile_image, presence: true
  validates :introduction, length: { maximum: 50 }
  validates :name, length: { in: 2..20 }, uniqueness: true

  has_many :books, dependent: :destroy

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:top, :about]

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def index
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: "You have created book successfully."
    else
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: "You have updated book successfully."
    else
      render :edit
    end
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @newbook = Book.new
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
      unless @book.user == current_user
        redirect_to books_path
      end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @book = @user.books
    @bookshow = Book.new
  end

  def index
    @users = User.all
    @bookindex = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

    def ensure_correct_user
    @user = User.find(params[:id])
      unless @user == current_user
        redirect_to users_path
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<h3>New book</h3>
<%= form_with model: book, url: books_path, method: :post do |f| %>
  <p>title</p>
  <%= f.text_field :title %>
  <p>Opinion</p>
  <%= f.text_area :body %>

  <%= f.submit "Create Book", class: "btn btn-success" %>
<% end %>

app/views/books/edit.html.erb
<p id="notice"></p>
<%= render "layouts/error", obj: @book %>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h3>Editing Book</h3>
      <%= form_with model: @book, url: book_path(@book.id), method: :patch do |f| %>
        <p>Title</p>
        <%= f.text_field :title, class: "form-control book_title" %>
        <p>Opinion</p>
        <%= f.text_area :body, class: "form-control book_body" %>
        <p>
        <%= f.submit "Update Book", class: "btn btn-success my-2" %>
        </p>
      <% end %>
      <%= link_to "戻る", books_path %>
      |
      <%= link_to "show", book_path(@book.id) %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<p id="notice"></p>
<%= render "layouts/error", obj: @book %>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/userinfo', user: current_user %>
      <%= render 'books/form', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h3>Book detail</h3>
        <table class="table">
          <tbody>
            <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(current_user) do %>
                  <%= image_tag book.user.get_profile_image(100, 100) %><br>
                  <%= book.user.name %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td><%= book.body %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/userinfo', user: @user %>
      <%= render 'books/form', book: @newbook %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h3>Book detail</h3>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(current_user) do %>
                <%= image_tag @book.user.get_profile_image(100, 100) %><br>
                <%= @book.user.name %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(@book.id) do %>
                <%= @book.title %>
              <% end %>
            </td>
            <td><%= @book.body %></td>
            <% if @book.user == current_user %>
            <td><%= link_to "edit", edit_book_path(@book.id), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to "destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-sm btn-danger" %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      Welcome to
      <i class="fas fa-book"></i>
      <strong>Bookers</strong>!</h1>
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>Welcome to
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>
        !!
      </h1>
      <p>
        In
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>
        ,
      </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_error.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h5><%= pluralize(obj.errors.count, "") %> 件のエラーが発生しました</h5>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SitePractice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
 <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand", href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li>
              <%= link_to user_path(current_user), class: "nav-link text-light" do %>
              <i class="fas fa-home"></i><span>Home</span>
              <% end %>
              </li>
              <li>
              <%= link_to users_path, class: "nav-link text-light" do %>
              <i class="fas fa-users"></i><span>Users</span>
              <% end %>
              </li>
              <li>
              <%= link_to books_path, class: "nav-link text-light" do %>
              <i class="fas fa-book-open"></i><span>Books</span>
              <% end %>
              </li>
              <li>
              <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
              <i class="fas fa-sign-out-alt"></i><span>Log out</span>
              <% end %>
              </li>
              <% else %>
              <li>
              <%= link_to  root_path, class: "nav-link text-light" do %>
              <i class="fas fa-home"></i><span>Home</span>
              <% end %>
              </li>
              <li>
              <%= link_to about_path, class: "nav-link text-light" do %>
              <i class="fas fa-link"></i><span>About</span>
              <% end %>
              </li>
              <li>
              <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
              <i class="fas fa-user-plus"></i><span>Sign up</span>
              <% end %>
              </li>
              <li>
              <%= link_to new_user_session_path, class: "nav-link text-light" do %>
              <i class="fas fa-sign-in-alt"></i><span>Log in</span>
              <% end %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <div class="notice-box">
        <p id="notice"><%= notice %></p>
      </div>
      <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_userinfo.html.erb
<h3>User info</h3>
<%= image_tag user.get_profile_image(100, 100) %>
<table class="table">
  <tdoby>
    <tr></tr>
    <tr>
      <th>name</th>
      <th><%= user.name%></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
  </tdoby>
</table>
<div class="row">
  <% if @user == current_user %>
  <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block edit_user_4481" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
  <% end%>
</div>

app/views/users/edit.html.erb
<p id="notice"></p>
<%= render "layouts/error", obj: @user %>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h3>User info</h3>
      <%= form_with model: @user, url: user_path(@user.id), method: :patch do |f| %>
        <p>Name</p>
        <%= f.text_field :name, class: "form-control book_title" %>
        <p>Image</p>
        <%= f.file_field :profile_image, accept: "image/*", class: "form-control-file user_image" %>
        <p>Introduction</p>
        <%= f.text_area :introduction, class: "form-control book_body" %>
        <p>
        <%= f.submit "Update Book", class: "btn btn-secondary my-2" %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/userinfo', user: current_user %>
      <%= render 'books/form', book: @bookindex %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h3>Users</h3>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td>
              <%= image_tag user.get_profile_image(100, 100) %><br>
            </td>
            <td>
              <%= user.name %>
            </td>
            <td><%= link_to "show", user_path(user.id) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/userinfo', user: @user %>
      <%= render 'books/form', book: @bookshow %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h3>Books</h3>
        <table class="table">
          <tbody>
            <% @book.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(@user.id) do %>
                  <%= image_tag book.user.get_profile_image(100, 100) %><br>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td><%= book.body %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>
</div>